### ISSUE TITLE
Allow connecting directly to unix socket

### ISSUE THREAD

**Issue by mwalbeck** [MetaProvide/talked-client#9]
Determine whether to use Unix socket or TCP to connect to the Talked server based on the scheme specified in the URI. So if the URI is `unix:///example/talked.sock` the client would connect to a Unix socket and if the URI is `https://talked.example.com` the client would connect over TCP.

**Comment by Kixunil** [comment]
I wouldn't mind if two slashes were dropped (so `unix:/foo/bar`) but if it's something mandated by curl best keep it as is.
